[theme]
base = "light"
primaryColor = "#f44610"
backgroundColor = "#f0f1f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#12141a"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
