[theme]
base = "dark"
primaryColor = "#13f460"
backgroundColor = "#0e0e0e"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
